<div id="sidebar">
	<div class="sidebar-head"><h4>Categorías</h4></div>
	<div class="sidebar-content">
		<ul class="plain-list">
			<li><a href="#">Agendas</a></li>
			<li><a href="#">Ánforas y termos</a></li>
			<li><a href="#">Bar</a></li>
			<li><a href="#">Belleza</a></li>
			<li><a href="#">Bolígrafos</a></li>
			<li><a href="#">Bolsas</a></li>
			<li><a href="#">Calculadoras</a></li>
			<li><a href="#">Carpetas y Calendarios</a></li>
			<li><a href="#">Deportes</a></li>
			<li><a href="#">Ecológicos</a></li>
			<li><a href="#">Entretenimiento</a></li>
			<li><a href="#">Gorras</a></li>
			<li><a href="#">Herramientas</a></li>
			<li><a href="#">Hieleras</a></li>
			<li><a href="#">Hogar</a></li>
			<li><a href="#">Impulsa</a></li>
			<li><a href="#">Infantil</a></li>
			<li><a href="#">Libretas</a></li>
			<li><a href="#">Llaveros</a></li>
			<li><a href="#">Mochilas</a></li>
			<li><a href="#">Oficina</a></li>
			<li><a href="#">Otra</a></li>
			<li><a href="#">Portafolios</a></li>
			<li><a href="#">Portarretratos</a></li>
			<li><a href="#">Reloj de pulso</a></li>
			<li><a href="#">Relojes</a></li>
			<li><a href="#">Salud</a></li>
			<li><a href="#">Soccer</a></li>
			<li><a href="#">Tazas</a></li>
			<li><a href="#">Tecnología</a></li>
			<li><a href="#">Textiles</a></li>
			<li><a href="#">Viajes</a></li>
		</ul>
	</div>
</div>